apiVersion: v1
kind: Secret
metadata:
  name: init-config-bundle-secret
data:
  config.yaml: U1VQRVJfVVNFUlM6Ci0gcXVheWFkbWluCkZFQVRVUkVfVVNFUl9DUkVBVElPTjogdHJ1ZQpGRUFUVVJFX1BST1hZX0NBQ0hFOiB0cnVlCg==